### ISSUE TITLE
installation problem -- or user error?

### ISSUE THREAD

**Issue by dbinetti** [fauno/jekyll-pandoc-multiple-formats#12]
apologies; i'm extremely new to ruby.  

I believe I have the gem installed 

```
gem list
...
jekyll (1.4.3)
jekyll-pandoc-multiple-formats (0.0.6)
```

and I believe my _config.yml is right

```
gems: [ 'jekyll-pandoc-multiple-formats' ]
name: Your New Jekyll Site
markdown: redcarpet
pygments: true

pandoc:
  skip: false
  impose: false
  output: ./tmp
  flags: '--smart --bibliography=ref.bib'
  site_flags: '--toc'
  outputs:
    pdf: '--latex-engine=latex'
    epub:
    markdown:
```

but I am getting this error:

```
$ jekyll build
Configuration file: /Users/dbinetti/Repos/foo/foo/_config.yml
/Users/dbinetti/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- jekyll-pandoc-multiple-formats (LoadError)
```

I am assuming this is user error, but am otherwise stuck.  Thanks.

**Comment by jpdevries** [comment]
I'm looking for installation instructions also. @dbinetti did you get it figured out?

**Comment by fauno** [comment]
we do it this way:

<https://github.com/edsl/endefensadelsl.org/blob/queue/_plugins/bundler.rb>

<https://github.com/edsl/endefensadelsl.org/blob/queue/Gemfile#L10>

you can also build the gem and install it on your jekyll site, just
clone this repo and run

    gem build jekyll-pandoc-multiple-formats.gemspec

i have yet to upload it to rubygems.org, sorry

-- 
.oÓ)
