### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by tomasparks** [fauno/jekyll-pandoc-multiple-formats#27]
help I cant install I get "ERROR:  Could not find a valid gem './jekyll-pandoc-multiple-formats.gem' (>= 0) in any repository" :(

> git clone https://github.com/fauno/jekyll-pandoc-multiple-formats.git
> Cloning into 'jekyll-pandoc-multiple-formats'...
> remote: Counting objects: 453, done.
> remote: Total 453 (delta 0), reused 0 (delta 0), pack-reused 453
> Receiving objects: 100% (453/453), 157.58 KiB | 111.00 KiB/s, done.
> Resolving deltas: 100% (229/229), done.
> Checking connectivity... done.
> tom@tom-HP-Pavilion-10-TS-Notebook-PC:~/Downloads/jekyll-pandoc-multiple-formats-master/jekyll-pandoc-multiple-formats$ gem build "./jekyll-pandoc-multiple-formats.gemspec"
> WARNING:  open-ended dependency on jekyll (>= 0) is not recommended
>   if jekyll is semantically versioned, use:
>     add_runtime_dependency 'jekyll', '~> 0'
> WARNING:  See http://guides.rubygems.org/specification-reference/ for help
>   Successfully built RubyGem
>   Name: jekyll-pandoc-multiple-formats
>   Version: 0.0.7
>   File: jekyll-pandoc-multiple-formats-0.0.7.gem
> tom@tom-HP-Pavilion-10-TS-Notebook-PC:~/Downloads/jekyll-pandoc-multiple-formats-master/jekyll-pandoc-multiple-formats$ gem install --local "./jekyll-pandoc-multiple-formats.gem"
> ERROR:  Could not find a valid gem './jekyll-pandoc-multiple-formats.gem' (>= 0) in any repository

`

**Comment by fauno** [comment]
tomasparks <notifications@github.com> writes:
>   File: jekyll-pandoc-multiple-formats-0.0.7.gem

you're missing the version number from the file name (try using the tab
key to autocomplete ;)

-- 
}(:=

**Comment by tomasparks** [comment]
doh
