### ISSUE TITLE
How to configure pandoc variants and additional extensions

### ISSUE THREAD

**Issue by v1kn** [fauno/jekyll-pandoc-multiple-formats#28]
the example from README:

    flags: '--smart'
    site_flags: '--toc'

does not include

* howto configure multiple flags - are they separated by commas or not?

* markdown variants - pandoc has multiple of them, Im interested in using `markdown_github`

* markdown extensions - like for example `fenced_code_attributes` or `footnotes`

on the command line it is done like so:

    pandoc -f markdown_github+footnoes+fenced_code_attributes

I'd like some advice on how to properly configure more advanced pandoc invocations inside `_config.yml`.
Thank You

**Comment by fauno** [comment]
>     flags: '--smart'
>     site_flags: '--toc'

>     pandoc -f markdown_github+footnoes+fenced_code_attributes

hi! flags are strings, so you can put all of them between quotes, like
this:

    flags: '--smart -f markdown_github+footnoes+fenced_code_attributes'

-- 
:D

**Comment by v1kn** [comment]
That's straightforwad enough, Thank You.

Your gem is quite useful, You should publish it to rubygems.org for more discoverability ;)
