### ISSUE TITLE
Blog post output paths are wrong

### ISSUE THREAD

**Issue by candlerb** [fauno/jekyll-pandoc-multiple-formats#9]
Using the default my-awesome-site jekyll site, with

```
pandoc:
  skip: false
  output: ./tmp
  outputs:
    pdf:
    epub:
```

Jekyll creates the required parent directory, e.g. `./tmp/pdf/jekyll/update/2013/11/20`, but then tries to write to `./tmp/pdf/jekyll/update/2013/11/20/jekyll/update/2013/11/20/welcome-to-jekyll.pdf` instead of `./tmp/pdf/jekyll/update/2013/11/20/welcome-to-jekyll.pdf`, and hence fails.

```
$ jekyll build
Configuration file: /Users/brian/tmp/my-awesome-site/_config.yml
            Source: /Users/brian/tmp/my-awesome-site
       Destination: /Users/brian/tmp/my-awesome-site/_site
      Generating... Creating ./tmp/pdf/jekyll/update/2013/11/20
pandoc  -o ./tmp/pdf/jekyll/update/2013/11/20/jekyll/update/2013/11/20/welcome-to-jekyll.pdf
pandoc: ./tmp/pdf/jekyll/update/2013/11/20/jekyll/update/2013/11/20/welcome-to-jekyll.pdf: openBinaryFile: does not exist (No such file or directory)
Creating ./tmp/epub/jekyll/update/2013/11/20
pandoc  -o ./tmp/epub/jekyll/update/2013/11/20/jekyll/update/2013/11/20/welcome-to-jekyll.epub
pandoc: ./tmp/epub/jekyll/update/2013/11/20/jekyll/update/2013/11/20/welcome-to-jekyll.epub: openBinaryFile: does not exist (No such file or directory)


done.
```

Tested with jekyll 1.3.0 under ruby 2.0.0p247

**Comment by vhuber** [comment]
Is there any pull request done @fauno @candlerb ?

**Comment by candlerb** [comment]
This is someone else's code which, as I said, I don't understand why it was written the way it was.  I think the author needs to make a decision as to whether the frig patch I made is in fact the correct solution, or there is something else underlying which needs to be changed.

**Comment by fauno** [comment]
the patch is already applied

https://github.com/fauno/jekyll-pandoc-multiple-formats/blob/master/lib/jekyll-pandoc-multiple-formats.rb#L21

i guess since it was so simple i just went ahead and applied it

-- 
http://librevpn.org.ar
